In [1]:
import os
import sys
import pandas as pd

# I. Transform 'class' conditioning into text

In [2]:
csv_path = '../data/raw/1000dataset.csv'

In [4]:
df=pd.read_csv(csv_path)
df.head()

,track_id,artists,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,360Wr96ywrCQq4kTAJ8Pq6,['Melanie Martinez'],80,220013,0.576,0.593,9,-6.024,0,0.0306,0.04670,0.000767,0.237,0.3730,157.993,4,electro
1,3yqoD9SYDfwvNEdU2NEpFx,['Rovalio'],50,146891,0.586,0.402,0,-10.913,0,0.0301,0.42100,0.903000,0.135,0.1550,150.012,4,electro
2,2ygvZOXrIeVL4xZmAWJT2C,['Billie Eilish'],72,208155,0.444,0.309,8,-10.956,1,0.0620,0.79500,0.132000,0.352,0.0875,104.745,4,electro
3,6HMT7AzGA5wmn5m2t1BuZR,"['Alan Walker', 'Steve Aoki', 'ISÁK', 'Omar No...",54,216053,0.521,0.819,6,-7.267,0,0.0413,0.00911,0.002270,0.086,0.1840,89.952,4,electro
4,0uLPKDuIhkIhttiwezNdiG,['Alec Benjamin'],66,171539,0.787,0.558,0,-5.237,1,0.0414,0.66400,0.000000,0.347,0.7060,94.049,4,electro

### 1) Extend dataset by creating new rows, one for each unique value in a lists of the attribute 'artists'. Thus, each spectrogram will be trained as many times as the different artists.

In [12]:
import pandas as pd
import ast

# Load the CSV file
file_path = csv_path
data = pd.read_csv(file_path)

# Initialize an empty list to store new rows
expanded_rows = []

# Iterate through each row to split rows with multiple artists
for _, row in data.iterrows():
    # Convert the artists column from string to a list
    artists_list = ast.literal_eval(row['artists']) if isinstance(row['artists'], str) else row['artists']
    
    # If only one artist, keep as is
    if len(artists_list) == 1:
        expanded_rows.append(row)
    else:
        # Create a new row for each artist
        for artist in artists_list:
            new_row = row.copy()
            new_row['artists'] = artist  # Set 'artists' to a single artist
            expanded_rows.append(new_row)

# Create a new DataFrame from the expanded rows
expanded_data = pd.DataFrame(expanded_rows)

# Display the first few rows of the expanded DataFrame
expanded_data.head()

'../data/raw/expanded_1000dataset.csv'

In [18]:
# Turn all the artists values into a string
def convert_artists(value):
    if isinstance(value, str) and value.startswith("[") and value.endswith("]"):
        try:
            # Convert string to list
            value = ast.literal_eval(value)
        except (ValueError, SyntaxError):
            pass
    # Convert to comma-separated string if value is a list
    if isinstance(value, list):
        return ', '.join(value)
    return value

# Apply the function to the 'artists' column
expanded_data['artists'] = expanded_data['artists'].apply(convert_artists)

In [19]:
expanded_data.head()

,track_id,artists,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,360Wr96ywrCQq4kTAJ8Pq6,Melanie Martinez,80,220013,0.576,0.593,9,-6.024,0,0.0306,0.04670,0.000767,0.237,0.3730,157.993,4,electro
1,3yqoD9SYDfwvNEdU2NEpFx,Rovalio,50,146891,0.586,0.402,0,-10.913,0,0.0301,0.42100,0.903000,0.135,0.1550,150.012,4,electro
2,2ygvZOXrIeVL4xZmAWJT2C,Billie Eilish,72,208155,0.444,0.309,8,-10.956,1,0.0620,0.79500,0.132000,0.352,0.0875,104.745,4,electro
3,6HMT7AzGA5wmn5m2t1BuZR,Alan Walker,54,216053,0.521,0.819,6,-7.267,0,0.0413,0.00911,0.002270,0.086,0.1840,89.952,4,electro
3,6HMT7AzGA5wmn5m2t1BuZR,Steve Aoki,54,216053,0.521,0.819,6,-7.267,0,0.0413,0.00911,0.002270,0.086,0.1840,89.952,4,electro

In [20]:
# Saving the transformed DataFrame to a new CSV file for the user
output_file_path = '../data/raw/expanded_1000dataset.csv'
expanded_data.to_csv(output_file_path, index=False)

output_file_path

'../data/raw/expanded_1000dataset.csv'

In [2]:
filepath='../data/raw/1000_textprompts.csv'

In [4]:
df=pd.read_csv(filepath)
df.head()

                 track_id             artists_genre
0  360Wr96ywrCQq4kTAJ8Pq6  Melanie Martinez electro
1  3yqoD9SYDfwvNEdU2NEpFx           Rovalio electro
2  2ygvZOXrIeVL4xZmAWJT2C     Billie Eilish electro
3  6HMT7AzGA5wmn5m2t1BuZR       Alan Walker electro
4  6HMT7AzGA5wmn5m2t1BuZR        Steve Aoki electro

In [ ]:
#

### 2) Transform class conditioning data of artist name and genre into text prompts with classes seperated by comma

In [2]:
import pandas as pd

# Load the CSV file into a DataFrame
csv_file = '../data/raw/expanded_1000dataset.csv'
df = pd.read_csv(csv_file)

# Concatenate 'artists' and 'track_genre' into a single string
df['artists_genre'] = df['artists'] + ' ' + df['track_genre']

# Select only 'track_id' and the new concatenated column
df_simplified = df[['track_id', 'artists_genre']]

# Display the transformed DataFrame
print(df_simplified)

# Optionally, save it to a new CSV file
df_simplified.to_csv('1000_textprompts.csv', index=False)

                    track_id             artists_genre
0     360Wr96ywrCQq4kTAJ8Pq6  Melanie Martinez electro
1     3yqoD9SYDfwvNEdU2NEpFx           Rovalio electro
2     2ygvZOXrIeVL4xZmAWJT2C     Billie Eilish electro
3     6HMT7AzGA5wmn5m2t1BuZR       Alan Walker electro
4     6HMT7AzGA5wmn5m2t1BuZR        Steve Aoki electro
...                      ...                       ...
1471  6qZyM6JV8ohLC4S2EL5sFh     Madhubanti Bagchi pop
1472  6qZyM6JV8ohLC4S2EL5sFh          Sachin-Jigar pop
1473  5zfRl79umXWvKoA7p4KEPa        Tanishk Bagchi pop
1474  5zfRl79umXWvKoA7p4KEPa          Udit Narayan pop
1475  5zfRl79umXWvKoA7p4KEPa           Alka Yagnik pop

[1476 rows x 2 columns]

CHECK FROM SPECTOGRAM TO MP3

In [18]:
image_path = "raw/spectrograms/0A0RBBTrgfq9eClnw6ZXT7.png"

In [ ]:
import numpy as np
import librosa
from PIL import Image
from pydub import AudioSegment
import soundfile as sf  # For saving audio files

def image_to_spectrogram(image_path):
    """
    Convert a spectrogram image to a numerical array representing the spectrogram.
    Assumes the spectrogram is grayscale, where pixel intensity represents dB values.
    """
    # Load the image
    img = Image.open(image_path).convert("L")  # Convert to grayscale ('L' mode)
    
    # Convert image to numpy array
    img_array = np.array(img)
    
    # Normalize the image to [0, 1] range (0 is minimum, 255 is maximum)
    img_array = img_array / 255.0

    # Convert the image intensities to dB scale (assuming they represent dB)
    # Rescale from [0, 1] to [-80 dB, 0 dB], as typical dB range for spectrograms is -80 to 0
    img_db = img_array * -80
    
    return img_db

def spectrogram_to_audio(spectrogram_db, sr=22050, hop_length=512):
    """
    Invert a dB-scaled spectrogram back to an audio waveform.
    """
    # Convert dB to amplitude
    spectrogram_amplitude = librosa.db_to_amplitude(spectrogram_db)
    
    # Perform the inverse Short-Time Fourier Transform (ISTFT) to recover the audio signal
    audio_signal = librosa.griffinlim(spectrogram_amplitude, hop_length=hop_length)
    
    return audio_signal

def save_as_mp3(audio_signal, sr, filename="output.mp3"):
    """
    Save the audio signal as an MP3 file using pydub.
    """
    # Save the audio signal as a temporary WAV file using soundfile
    sf.write("temp.wav", audio_signal, sr)  # Use soundfile to save as WAV
    
    # Convert the WAV file to MP3 using pydub
    sound = AudioSegment.from_wav("temp.wav")
    sound.export(filename, format="mp3")
    print(f"Saved MP3 as {filename}")

# Example usage
if __name__ == "__main__":
    # Path to the spectrogram image (PNG)
    image_path = "raw/spectrograms/0A0RBBTrgfq9eClnw6ZXT7.png"
    
    # Step 1: Convert the image to a spectrogram
    spectrogram_db = image_to_spectrogram(image_path)
    
    # Step 2: Convert the spectrogram to an audio signal
    audio_signal = spectrogram_to_audio(spectrogram_db, sr=22050)
    
    # Step 3: Save the audio signal as MP3
    save_as_mp3(audio_signal, sr=22050, filename="output.mp3")

In [1]:
import torch
torch.cuda.empty_cache()

audio shape ???
sample rate ???

Download everything in wav? or find a solution in another way ?